/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { CallToServerCallback, CancelCallback, ConfirmCallback } from "./components/echo-console/types";
import { LoadObjectsCallback, ObjectType, OpenObjectCallback } from "./components/object-selector/types";
export { CallToServerCallback, CancelCallback, ConfirmCallback } from "./components/echo-console/types";
export { LoadObjectsCallback, ObjectType, OpenObjectCallback } from "./components/object-selector/types";
export namespace Components {
    interface SvEchoConsole {
        "callToServerCallback": CallToServerCallback;
        "cancelCallback": CancelCallback;
        "confirmCallback": ConfirmCallback;
    }
    interface SvObjectSelector {
        /**
          * Callback invoked to load objects (filtered by selected type)
         */
        "loadObjectsCallback": LoadObjectsCallback;
        /**
          * The available object types.
         */
        "objectTypes": ObjectType[];
        /**
          * Callback invoked to open the selected objects
         */
        "openObjectCallback": OpenObjectCallback;
    }
}
declare global {
    interface HTMLSvEchoConsoleElement extends Components.SvEchoConsole, HTMLStencilElement {
    }
    var HTMLSvEchoConsoleElement: {
        prototype: HTMLSvEchoConsoleElement;
        new (): HTMLSvEchoConsoleElement;
    };
    interface HTMLSvObjectSelectorElement extends Components.SvObjectSelector, HTMLStencilElement {
    }
    var HTMLSvObjectSelectorElement: {
        prototype: HTMLSvObjectSelectorElement;
        new (): HTMLSvObjectSelectorElement;
    };
    interface HTMLElementTagNameMap {
        "sv-echo-console": HTMLSvEchoConsoleElement;
        "sv-object-selector": HTMLSvObjectSelectorElement;
    }
}
declare namespace LocalJSX {
    interface SvEchoConsole {
        "callToServerCallback": CallToServerCallback;
        "cancelCallback": CancelCallback;
        "confirmCallback": ConfirmCallback;
    }
    interface SvObjectSelector {
        /**
          * Callback invoked to load objects (filtered by selected type)
         */
        "loadObjectsCallback": LoadObjectsCallback;
        /**
          * The available object types.
         */
        "objectTypes"?: ObjectType[];
        /**
          * Callback invoked to open the selected objects
         */
        "openObjectCallback": OpenObjectCallback;
    }
    interface IntrinsicElements {
        "sv-echo-console": SvEchoConsole;
        "sv-object-selector": SvObjectSelector;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sv-echo-console": LocalJSX.SvEchoConsole & JSXBase.HTMLAttributes<HTMLSvEchoConsoleElement>;
            "sv-object-selector": LocalJSX.SvObjectSelector & JSXBase.HTMLAttributes<HTMLSvObjectSelectorElement>;
        }
    }
}
